#!/bin/sh

set -e

TEXLIVE_BST_DIR_OLD=/usr/share/texmf-texlive/bibtex/bst/nrtex
TEXLIVE_BST_DIR_NEW=/usr/share/texlive/texmf-dist/bibtex/bst/nrtex

if [ -d $TEXLIVE_BST_DIR_OLD ]; then
    rm -rf $TEXLIVE_BST_DIR_OLD
elif [ -d $TEXLIVE_BST_DIR_NEW ]; then
    rm -rf $TEXLIVE_BST_DIR_NEW
fi

#DEBHELPER#

exit 0
