name: Debuild CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run Install Commands
      run: sudo apt-get install devscripts
          
    - name: Build installation package
      run: |
            debuild -- clean
            debuild -us -uc -bmake
